server:
  port: 15000

logging:
  level: debug

spring:
  application:
    name: file-upload-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 200MB
      max-request-size: 220MB
