
ftpconfig:
  host: localhost
  port: 22
  username: luotao
  password: 123456
  clientMode: 0
  fileType: 2
  bufferSize: 100000

logging:
  level:
    com.brotao.sc: debug
    org.springframework.integration: debug

app:
  inner-server:
    sftps:
      - host: 10.106.0.221
        user: root
        password: Hundsun@1
        allowUnknownKeys: true
      - host: 10.106.0.220
        user: root
        password: tAR4UZyD
        allowUnknownKeys: true
      - host: 10.106.0.219
        user: root
        password: Ax8Ainy7
        allowUnknownKeys: true
